{{- if .Values.console.enabled }}
{{- $values := .Values.console.ui -}}
{{- $context := dict "Values" (merge (deepCopy $values) (dict "global" .Values.global "console" .Values.console "composite" .Values.composite)) "Chart" .Chart "Release" .Release "Files" .Files "Capabilities" .Capabilities -}}
{{- with $context -}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agriComposite.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
{{- end }}
{{- end -}}
{{- end }}
